<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' В данной компании подбирали подарок шефу. Сотрудники  Зеленбума предложили массу вариантов из ретро сувениров. В итоге купили отличный востановленный самовар. Самое главное - именнинику угодили. Думаю, обязательно вернемся еще за нестандартными презентами.' => 'In this company they picked a present for the boss. Employees Zelenbum offered a lot of options from retro souvenirs. As a result, bought an excellent vostanovlenny samovar. The most important thing is that the name-list was pleased. I think we will definitely return for non-standard presentations.',
    ' Я очень рада связать судьбу моего Сада с вами! Мы только начинаем сотрудничать, но я уже сейчас получаю массу удовольствия от нашей совместной работы, и надеюсь, мой сад с вашей помощью превратиться в "Сад моей мечты".' => 'I am very happy to connect the fate of my Garden with you! We are just starting to cooperate, but now I am getting a lot of pleasure from our teamwork, and I hope my garden with your help will turn into the "Garden of my dreams".',
    '*Введите корректрый емейл.' => '*Please enter a valid email.',
    '*Поле обязательное к заполнению.' => '*This field is required.',
    'Ассортимент' => 'Assortiments',
    'Ваша корзина : ' => 'Your shopping cart:',
    'Все права защищены' => 'All rights reserved',
    'Выезд из Запорожья, п. Балабино.' => 'Departure from Zaporozhye, Balabino.',
    'Добавить в корзину' => 'Add to cart',
    'Заказывали материалы для благоустройства участка в 2016 году, остались довольны сотруднечеством.' => 'Ordered materials for the improvement of the site in 2016, were satisfied with the cooperation.',
    'Заметки' => 'Notes',
    'Зеленбум' => 'Zelenbum',
    'Камень' => 'A rock',
    'Количество' => 'Quantity',
    'Компания "Зеленбум" существует уже более 16 лет и является одной из ведущих компаний по комплексному снабжению материалами для строительства и благоутсройства територии. <br>Занимаемся переработкой и реализацией ланшафтного камня, отделочной и облицовочной плитки. Изготавливаем беседки, перголы, садовую мебель, кованые изделия. В наличии большой ассортимент плетеной мебели и ретро-сувениров.' => 'The company "Zelenbum" has existed for more than 16 years and is one of the leading companies in the complex supply of materials for the construction and prosperity of the territory. <br> We are engaged in processing and selling lanshaftnogo stone, finishing and facing tiles. We produce gazebos, pergolas, garden furniture, forged products. There is a wide range of wicker furniture and retro souvenirs.',
    'Купить' => 'Buy',
    'Наши работы' => 'Our works',
    'Напишите нам' => 'Contact Us',
    'Наши координаты' => 'Our coordinates',
    'Обшая сумма:' => 'Total amount:',
    'Обшая сумма: ' => 'Total amount: ',
    'Отправить' => 'Send',
    'Подчеркните Вашу индивидуальность!' => 'Emphasize your personality!',
    'Ретро сувениры' => 'Retro souvenirs',
    'Садовая мебель' => 'Garden furniture',
    'Сумма' => 'Amount',
    'Телефон' => 'Phone',
    'Телефон:' => 'Phone',
    'Украина, Запорожье' => 'Ukraine, Zaporozhye',
    'Цена' => 'Price',
    'Цена : ' => 'Price : ',
    'Что о нас говорят' => 'What they say about us',
    'имя' => 'name',
    'пуста' => 'empty',
    'сообщение' => 'message',
    'телефон' => 'phone',
];
