<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' В данной компании подбирали подарок шефу. Сотрудники  Зеленбума предложили массу вариантов из ретро сувениров. В итоге купили отличный востановленный самовар. Самое главное - именнинику угодили. Думаю, обязательно вернемся еще за нестандартными презентами.' => 'In this company they picked a present for the boss. Employees Zelenbum offered a lot of options from retro souvenirs. As a result, bought an excellent vostanovlenny samovar. The most important thing is that the name-list was pleased. I think we will definitely return for non-standard presentations.',
    ' Я очень рада связать судьбу моего Сада с вами! Мы только начинаем сотрудничать, но я уже сейчас получаю массу удовольствия от нашей совместной работы, и надеюсь, мой сад с вашей помощью превратиться в "Сад моей мечты".' => 'I am very happy to connect the fate of my Garden with you! We are just starting to cooperate, but now I am getting a lot of pleasure from our teamwork, and I hope my garden with your help will turn into the "Garden of my dreams".',
    '*Введите корректрый емейл.' => '*Please enter a valid email.',
    '*Поле обязательное к заполнению.' => '*This field is required.',
    'Ассортимент' => 'Assortiments',
    'Ваша корзина : ' => 'Your shopping cart:',
    'Все права защищены' => 'All rights reserved',
    'Выезд из Запорожья, п. Балабино.' => 'Departure from Zaporozhye, Balabino.',
    'Данные отправлены. Мы свяжемся с Вами в ближайшее время.' => 'The data has been sent. We will contact you shortly.',
    'Для внутренней и наружной облицовки используют природный экологически чистый камень. У нас вы можете найти песчаник, известняк, ракушечник, сланец, кварцит, андезит, травертин, цеалит, различных форм и размеров. Цвет: белый, светло-желтый, бирюзовый, серебристо-розовый, желтый, горчичный, оливковый, коричневый, бордовый, темно-зеленый, черный.' => 'For indoor and outdoor facing use a natural environmentally friendly stone. Here you can find sandstone, limestone, shell rock, slate, quartzite, andesite, travertine, celite, of various shapes and sizes. Color: white, light yellow, turquoise, silvery-pink, yellow, mustard, olive, brown, burgundy, dark green, black.',
    'Добавить в корзину' => 'Add to cart',
    'Если Вы ищите что-то необычное, "с историей" на подарок или для себя, Вы не ошиблись. В Зеленбум есть все, начиная от ретро-посуды и старинных элементов быта, и вплоть до ретро-авто, и оружия.' => 'If you are looking for something unusual, "with a history" for a gift or for yourself, you are not mistaken. In Zelenbum there is everything, from retro utensils and ancient elements of life, and up to retro cars, and weapons.',
    'Заказывали материалы для благоустройства участка в 2016 году, остались довольны сотруднечеством.' => 'Ordered materials for the improvement of the site in 2016, were satisfied with the cooperation.',
    'Заметки' => 'Notes',
    'Зеленбум' => 'Zelenbum',
    'Камень' => 'A rock',
    'Количество' => 'Quantity',
    'Компания "Зеленбум" существует уже более 16 лет и является одной из ведущих компаний по комплексному снабжению материалами для строительства и благоутсройства територии. <br>Занимаемся переработкой и реализацией ланшафтного камня, отделочной и облицовочной плитки. Изготавливаем беседки, перголы, садовую мебель, кованые изделия. В наличии большой ассортимент плетеной мебели и ретро-сувениров.' => 'The company "Zelenbum" has existed for more than 16 years and is one of the leading companies in the complex supply of materials for the construction and prosperity of the territory. <br> We are engaged in processing and selling lanshaftnogo stone, finishing and facing tiles. We produce gazebos, pergolas, garden furniture, forged products. There is a wide range of wicker furniture and retro souvenirs.',
    'Купить' => 'Buy',
    'Лавочка' => 'Bench',
    'Лавочка садовая' => 'Garden benches',
    'Ландшафтный камень' => 'Landscaping stone',
    'Напишите нам' => 'Contact Us',
    'Наши координаты' => 'Our coordinates',
    'Наши работы' => 'Our works',
    'Невозможно выполнить заказ. Пожалуйста свяжитесь с нами.' => 'Cannot place your order. Please contact us.',
    'Обшая сумма:' => 'Total amount:',
    'Обшая сумма: ' => 'Total amount: ',
    'Отправить' => 'Send',
    'Подчеркните Вашу индивидуальность!' => 'Emphasize your personality!',
    'Ретро сувениры' => 'Retro souvenirs',
    'Садовая мебель' => 'Garden furniture',
    'Садовая беседка' => 'Garden arbor',
    'Садовая мебель наиболее актуальна в теплые сезоны: весна-лето и начало осени, когда большую часть времени хочется проводить на свежем воздухе. У нас широкий выбор мебели для сада - столов, стульев, диванов, комплектов для улицы из различных материалов.' => 'Garden furniture is most relevant in the warm seasons: spring-summer and early autumn, when most of the time you want to spend in the fresh air. We have a wide selection of furniture for garden - tables, chairs, sofas, outdoor kits from various materials.',
    'Спасибо за ваш заказ. Мы скоро свяжемся с вами.' => 'Thanks for your order. We\'ll contact you soon.',
    'Сумма' => 'Amount',
    'Телефон' => 'Phone',
    'Телефон:' => 'Phone',
    'Украина, Запорожье' => 'Ukraine, Zaporozhye',
    'Цена' => 'Price',
    'Цена : ' => 'Price : ',
    'Что о нас говорят' => 'What they say about us',
    'имя' => 'name',
    'пустая' => 'empty',
    'сообщение' => 'message',
    'телефон' => 'phone',
    'Садовый комплект' => 'Garden kit',
    'Садовый комплект впишется в изысканный интерьер' => 'Garden kit will fit into the refined interior',
    'Дерево ясень. Высококачественная работа. Эта лавочка может не только украсить Вашу усадьбу, но подчеркнуть индивидуальность Вашей кухни или гостиной.' => 'The tree is ash. High-quality work. This shop can not only decorate your estate, but emphasize the individuality of your kitchen or living room.',
    'Беседка выполнена в стиле ретро' => 'The arbor is made in the style of retro',
    'Дерево - ясень. Работа выполнена на высшем уровне! Наши мастера прикладывают все усилия для Вашего комфорта. Эта лавочка может не только украсить Вашу усадьбу, но подчеркнуть индивидуальность Вашей кухни или гостиной.' => 'The tree is ash. The work is done at the highest level! Our masters make every effort for your comfort. This shop can not only decorate your estate, but emphasize the individuality of your kitchen or living room.',
    'Песчаник' => 'Sandstone',
    'Не торцованный, рустованный' => 'Not tinted, rusted',
    'Валун' => 'Boulder',
    'Вес: 0,5 – 10 кг. ' => 'Weight: 0.5 - 10 kg.',
    'Кварцит розовый' => 'Quartzite pink',
    'окатанный' => 'rounded',
    'Плитка кратная' => 'Tile multiple',
    'Толщина: 1-2см' => 'Thickness: 1-2cm',
];
